# Commands for testing and development

version: '3.7'

services:

  base: &base
    build: .
    platform: "linux/amd64"
    ports:
      - "8080:8080"
      - "5900:5900"
    volumes:
      - ..:/airflow/dataplatform
      - /tmp/airflow/data:/data
      - ~/.aws/:/airflow/.aws:ro
    image: airflow
    environment:
      - ENV=development
      - START_XVFB=false
      - AIRFLOW_TEST=1
      - PYTHONPATH=/airflow/dataplatform/airflow/dags:$PYTHONPATH
    env_file: local.env
    entrypoint: /airflow/dataplatform/airflow/dev_entrypoint.sh
    depends_on:
      - db

  db:
    platform: "linux/amd64"
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=airflow
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - metadata_db:/var/lib/mysql

    command: 
      - mysqld
      - --explicit-defaults-for-timestamp
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
volumes:
  metadata_db:
